<?php echo $this->render('pre-content.phtml'); ?>

<div class="cardArea">
    <?php if (empty($this->errors)): ?>
        <div class="definitionCard main">
            <span class="definitionTerm">
                <?php echo $this->mainTerm; ?>
            </span>

            <br/>

            <span class="definitionDescription">
                <?php echo $this->mainDescription; ?>
            </span>
        </div>
    <?php else: ?>
        <div class="errors">
            <?php foreach ($this->errors as $error): ?>
                <span class="error"><?php echo $error?></span>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>

<?php echo $this->render('post-content.phtml'); ?>