<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Glossar</title>
        <link rel="icon" type="image/png" href="<?php echo $this->url('favicon.png'); ?>"/>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->url('styles/default-style.css'); ?>"/>
        <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
        <script src="<?php echo $this->url('scripts/definition.js'); ?>" async defer></script>
    </head>

    <body>
        <header>
            <h1>
                <img src="<?php echo $this->url('favicon.png'); ?>" alt="(?)" />
                <a href="<?php echo $this->url('/'); ?>">Glossar</a>
            </h1>
        </header>
