<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Warp zone</title>
        <link rel="icon" type="image/png" href="favicon.png"/>
        <link href="styles/<%ph id="activeTheme" %>.css" rel="stylesheet" type="text/css"/>
        <script type="text/javascript"><?php echo $this->getInlineJavascript(); ?></script>
    </head>

    <body>
        <div id="header">
            <h3 class="headerTitle">Warp zone</h3>
            <form id="entryForm" method="post" action="generate_index.php">
                <div class="inputField">
                    <span class="inputLabel">URL</span><br/>
                    <input class="textInput" type="text" name="url"/>
                </div>

                <div class="inputField">
                    <span class="inputLabel">Name</span><br/>
                    <input class="textInput" type="text" name="displayName"/>
                </div>

                <div class="inputField">
                    <span class="inputLabel">Section</span><br/>
                    <select class="selectInput" name="section">
                        <%ph id="selectOptions"%>
                    </select>
                </div>

                <div class="inputField">
                    <span class="inputLabel">or: New section</span><br/>
                    <input class="textInput" name="newSection" />
                </div>

                <div class="inputField">
                    <input class="submitButton actionButton" type="submit" name="submit" value="Submit"/>
                </div>
            </form>

            <a href="generate_index.php">
                <div class="actionButton" id="rebuildPage">Rebuild</div>
            </a>

            <form id="themeForm" method="post" action="generate_index.php">
                <div class="inputField">
                    <span class="inputLabel">Pick theme</span><br/>
                    <select class="selectInput" name="theme">
                        <%ph id="themeOptions" %>
                    </select>
                </div>

                <a href="generate_index.php">
                    <input class="submitButton actionButton" type="submit" name="submit" value="Apply"/>
                </a>
            </form>
        </div>