<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Warp zone</title>
        <link rel="icon" type="image/png" href="favicon.png"/>
        <link href="styles/default.css" rel="stylesheet" type="text/css"/>
        <script type="text/javascript"><?php echo $this->getInlineJavascript(); ?></script>
    </head>

    <body>
        <div id="header">
            <h3 class="headerTitle">Warp zone</h3>
        </div>

        <div id="content">
            <h1>Register</h1>

            <form action="<?php echo $this->url('/register'); ?>" method="post" name="registerForm" id="registerForm">
                <input type="text" name="email" id="email" placeholder="Email"></input>
                <input type="text" name="name" id="name" placeholder="Username"></input>
                <input type="password" name="password" id="password" placeholder="Password"></input>
                <input type="password" name="repeat" id="repeat" placeholder="Repeat password"></input>
                <input type="submit" name="submit" id="submit"></input>
            </form>
        </div>
    </body>
</html>